"""add_report_history_table

Revision ID: 26187a5d80e0
Revises: c87967f75b09
Create Date: 2026-05-16 10:58:11.655770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26187a5d80e0'
down_revision: Union[str, Sequence[str], None] = 'c87967f75b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staging_imports')
    op.drop_index(op.f('idx_ct_campaign'), table_name='campaign_targets')
    op.drop_index(op.f('idx_ct_phone'), table_name='campaign_targets')
    op.drop_table('campaign_targets')
    op.drop_index(op.f('ix_churn_scores_cache_generated_at'), table_name='churn_scores_cache')
    op.drop_index(op.f('ix_churn_scores_cache_risk'), table_name='churn_scores_cache')
    op.drop_table('churn_scores_cache')
    op.drop_index(op.f('ix_seg_assign_generated_at'), table_name='segmentation_assignments')
    op.drop_index(op.f('ix_seg_assign_service_win'), table_name='segmentation_assignments')
    op.drop_table('segmentation_assignments')
    op.drop_index(op.f('ix_seg_train_logs_job_id'), table_name='segmentation_training_job_logs')
    op.drop_table('segmentation_training_job_logs')
    op.drop_index(op.f('ix_seg_train_jobs_started_at'), table_name='segmentation_training_jobs')
    op.drop_table('segmentation_training_jobs')
    op.drop_index(op.f('idx_user_features_churn_segment'), table_name='user_features')
    op.drop_index(op.f('idx_user_features_segment'), table_name='user_features')
    op.drop_index(op.f('idx_user_features_updated_at'), table_name='user_features')
    op.drop_table('user_features')
    op.create_table_comment(
        'analyst_notes',
        'Analyst contextual notes',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('idx_billing_events_datetime_status'), table_name='billing_events')
    op.drop_index(op.f('idx_billing_events_service_datetime'), table_name='billing_events')
    op.drop_index(op.f('idx_billing_events_sub_failed_dt'), table_name='billing_events', postgresql_where="((status)::text = 'failed'::text)")
    op.drop_index(op.f('idx_billing_events_sub_success_dt'), table_name='billing_events', postgresql_where="((status)::text = 'success'::text)")
    op.drop_index(op.f('idx_billing_events_user_datetime'), table_name='billing_events')
    op.drop_index(op.f('ix_be_subscription_event_status'), table_name='billing_events')
    op.drop_index(op.f('idx_campaigns_service_send_datetime'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_service_send_datetime'), table_name='campaigns')
    op.drop_index(op.f('idx_cohorts_service_cohort_date'), table_name='cohorts')
    op.drop_index(op.f('idx_cohorts_service_id'), table_name='cohorts')
    op.create_table_comment(
        'platform_user_invites',
        'Pending platform user invites',
        existing_comment=None,
        schema=None
    )
    op.alter_column('platform_users', 'reset_token',
               existing_type=sa.VARCHAR(length=255),
               comment='Token de réinitialisation de mot de passe',
               existing_nullable=True)
    op.alter_column('platform_users', 'reset_token_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Expiration du token de réinitialisation',
               existing_nullable=True)
    op.drop_index(op.f('ix_platform_users_reset_token'), table_name='platform_users')
    # Backfill sms_events.user_id before enforcing NOT NULL.
    # 1) Create users for missing phone numbers present in sms_events rows with NULL user_id.
    op.execute(
        """
        INSERT INTO users (id, phone_number, status)
        SELECT gen_random_uuid(), se.phone_number, 'active'
        FROM (
          SELECT DISTINCT phone_number
          FROM sms_events
          WHERE user_id IS NULL
            AND phone_number IS NOT NULL
            AND btrim(phone_number) <> ''
        ) se
        WHERE NOT EXISTS (
          SELECT 1
          FROM users u
          WHERE u.phone_number = se.phone_number
        )
        """
    )
    # 2) Link sms_events NULL user_id rows to users by phone_number.
    op.execute(
        """
        UPDATE sms_events se
        SET user_id = u.id
        FROM users u
        WHERE se.user_id IS NULL
          AND se.phone_number IS NOT NULL
          AND btrim(se.phone_number) <> ''
          AND u.phone_number = se.phone_number
        """
    )
    # 3) Ensure a fallback placeholder user for any remaining NULL user_id rows.
    op.execute(
        """
        INSERT INTO users (id, phone_number, status)
        VALUES ('00000000-0000-0000-0000-000000000001', '__unknown_sms_user__', 'inactive')
        ON CONFLICT (phone_number) DO NOTHING
        """
    )
    op.execute(
        """
        UPDATE sms_events
        SET user_id = '00000000-0000-0000-0000-000000000001'
        WHERE user_id IS NULL
        """
    )

    op.alter_column('sms_events', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('idx_sms_events_event_type_event_datetime'), table_name='sms_events')
    op.drop_index(op.f('idx_sms_events_metadata_gin'), table_name='sms_events', postgresql_using='gin')
    op.drop_index(op.f('idx_sms_events_source_system'), table_name='sms_events')
    op.drop_index(op.f('idx_sms_evt_activation_channel'), table_name='sms_events')
    op.drop_index(op.f('idx_sms_evt_activation_channel_dt'), table_name='sms_events')
    op.drop_index(op.f('idx_sms_evt_activation_partial'), table_name='sms_events', postgresql_where='(is_activation = true)')
    op.drop_index(op.f('idx_sms_evt_channel'), table_name='sms_events')
    op.drop_index(op.f('idx_sms_evt_delivery_status'), table_name='sms_events')
    op.drop_index(op.f('idx_sms_evt_delivery_status_dt'), table_name='sms_events')
    op.drop_index(op.f('idx_sms_evt_dt_channel'), table_name='sms_events')
    op.drop_index(op.f('idx_sms_evt_event_datetime'), table_name='sms_events')
    op.drop_index(op.f('idx_sms_evt_event_type'), table_name='sms_events')
    op.drop_index(op.f('idx_sms_evt_failed_delivery_partial'), table_name='sms_events', postgresql_where="((delivery_status)::text = 'FAILED'::text)")
    op.drop_index(op.f('idx_sms_evt_is_activation'), table_name='sms_events')
    op.drop_index(op.f('idx_sms_evt_is_otp'), table_name='sms_events')
    op.drop_index(op.f('idx_sms_evt_otp_partial'), table_name='sms_events', postgresql_where='(is_otp = true)')
    op.drop_index(op.f('idx_sms_evt_service_dt'), table_name='sms_events')
    op.drop_index(op.f('idx_sms_evt_service_id'), table_name='sms_events')
    op.drop_index(op.f('idx_sms_evt_user_dt'), table_name='sms_events')
    op.drop_index(op.f('idx_sms_evt_user_id'), table_name='sms_events')
    op.drop_column('sms_events', 'activation_channel')
    op.drop_column('sms_events', 'template_code')
    op.drop_column('sms_events', 'website_path')
    op.drop_column('sms_events', 'phone_number')
    op.drop_column('sms_events', 'template_name')
    op.drop_column('sms_events', 'session_id')
    op.drop_column('sms_events', 'otp_code')
    op.drop_column('sms_events', 'event_result')
    op.drop_column('sms_events', 'is_otp')
    op.drop_column('sms_events', 'activation_status')
    op.drop_column('sms_events', 'failure_reason')
    op.drop_column('sms_events', 'channel')
    op.drop_column('sms_events', 'external_ref')
    op.drop_column('sms_events', 'landing_page')
    op.drop_column('sms_events', 'metadata')
    op.drop_column('sms_events', 'flow_name')
    op.drop_column('sms_events', 'is_activation')
    op.drop_column('sms_events', 'ussd_code')
    op.drop_column('sms_events', 'source_system')
    op.drop_column('sms_events', 'shortcode')
    op.drop_index(op.f('idx_subscriptions_end_date'), table_name='subscriptions')
    op.drop_index(op.f('idx_subscriptions_service_end'), table_name='subscriptions')
    op.drop_index(op.f('idx_subscriptions_service_start_date'), table_name='subscriptions')
    op.drop_index(op.f('idx_subscriptions_service_start_user'), table_name='subscriptions')
    op.drop_index(op.f('idx_subscriptions_status_end_date'), table_name='subscriptions')
    op.drop_index(op.f('idx_subscriptions_status_service_end_partial'), table_name='subscriptions', postgresql_where="((status)::text = ANY ((ARRAY['cancelled'::character varying, 'expired'::character varying])::text[]))")
    op.drop_index(op.f('ix_sub_service_window'), table_name='subscriptions')
    op.drop_index(op.f('ix_sub_user_service_window'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_campaign_null_service_start'), table_name='subscriptions', postgresql_where='(campaign_id IS NULL)')
    op.drop_index(op.f('idx_unsub_datetime'), table_name='unsubscriptions')
    op.drop_index(op.f('idx_unsub_reason'), table_name='unsubscriptions')
    op.drop_index(op.f('idx_unsub_service_id'), table_name='unsubscriptions')
    op.drop_index(op.f('idx_unsub_sub_id'), table_name='unsubscriptions')
    op.drop_index(op.f('idx_unsub_user_id'), table_name='unsubscriptions')
    op.drop_index(op.f('idx_unsubscriptions_datetime_service'), table_name='unsubscriptions')
    op.drop_index(op.f('idx_user_activities_datetime_type'), table_name='user_activities')
    op.drop_index(op.f('idx_user_activities_datetime_user'), table_name='user_activities')
    op.drop_index(op.f('idx_user_activities_service_datetime'), table_name='user_activities')
    op.drop_index(op.f('idx_user_activities_service_datetime_user'), table_name='user_activities')
    op.drop_index(op.f('idx_user_activities_service_id'), table_name='user_activities')
    op.drop_index(op.f('idx_user_activities_service_user_dt'), table_name='user_activities')
    op.alter_column('users', 'channel',
               existing_type=sa.VARCHAR(length=20),
               comment='Activation channel from source (USSD/WEB)',
               existing_nullable=True)
    op.drop_index(op.f('idx_users_status_last_activity'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_status_last_activity'), 'users', ['status', 'last_activity_at'], unique=False)
    op.alter_column('users', 'channel',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Activation channel from source (USSD/WEB)',
               existing_nullable=True)
    op.create_index(op.f('idx_user_activities_service_user_dt'), 'user_activities', ['service_id', 'user_id', 'activity_datetime'], unique=False)
    op.create_index(op.f('idx_user_activities_service_id'), 'user_activities', ['service_id'], unique=False)
    op.create_index(op.f('idx_user_activities_service_datetime_user'), 'user_activities', ['service_id', 'activity_datetime', 'user_id'], unique=False)
    op.create_index(op.f('idx_user_activities_service_datetime'), 'user_activities', ['service_id', 'activity_datetime'], unique=False)
    op.create_index(op.f('idx_user_activities_datetime_user'), 'user_activities', ['activity_datetime', 'user_id'], unique=False)
    op.create_index(op.f('idx_user_activities_datetime_type'), 'user_activities', ['activity_datetime', 'activity_type'], unique=False)
    op.create_index(op.f('idx_unsubscriptions_datetime_service'), 'unsubscriptions', ['unsubscription_datetime', 'service_id'], unique=False)
    op.create_index(op.f('idx_unsub_user_id'), 'unsubscriptions', ['user_id'], unique=False)
    op.create_index(op.f('idx_unsub_sub_id'), 'unsubscriptions', ['subscription_id'], unique=False)
    op.create_index(op.f('idx_unsub_service_id'), 'unsubscriptions', ['service_id'], unique=False)
    op.create_index(op.f('idx_unsub_reason'), 'unsubscriptions', ['churn_reason'], unique=False)
    op.create_index(op.f('idx_unsub_datetime'), 'unsubscriptions', ['unsubscription_datetime'], unique=False)
    op.create_index(op.f('ix_subscriptions_campaign_null_service_start'), 'subscriptions', ['service_id', 'subscription_start_date'], unique=False, postgresql_where='(campaign_id IS NULL)')
    op.create_index(op.f('ix_sub_user_service_window'), 'subscriptions', ['user_id', 'service_id', 'subscription_start_date', 'subscription_end_date'], unique=False)
    op.create_index(op.f('ix_sub_service_window'), 'subscriptions', ['service_id', 'subscription_start_date', 'subscription_end_date'], unique=False)
    op.create_index(op.f('idx_subscriptions_status_service_end_partial'), 'subscriptions', ['service_id', 'subscription_end_date'], unique=False, postgresql_where="((status)::text = ANY ((ARRAY['cancelled'::character varying, 'expired'::character varying])::text[]))")
    op.create_index(op.f('idx_subscriptions_status_end_date'), 'subscriptions', ['status', 'subscription_end_date'], unique=False)
    op.create_index(op.f('idx_subscriptions_service_start_user'), 'subscriptions', ['service_id', 'subscription_start_date', 'user_id'], unique=False)
    op.create_index(op.f('idx_subscriptions_service_start_date'), 'subscriptions', ['service_id', 'subscription_start_date'], unique=False)
    op.create_index(op.f('idx_subscriptions_service_end'), 'subscriptions', ['service_id', 'subscription_end_date'], unique=False)
    op.create_index(op.f('idx_subscriptions_end_date'), 'subscriptions', ['subscription_end_date'], unique=False)
    op.add_column('sms_events', sa.Column('shortcode', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('sms_events', sa.Column('source_system', sa.VARCHAR(length=50), server_default=sa.text("'hawala.message_events'::character varying"), autoincrement=False, nullable=False))
    op.add_column('sms_events', sa.Column('ussd_code', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('sms_events', sa.Column('is_activation', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('sms_events', sa.Column('flow_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sms_events', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('sms_events', sa.Column('landing_page', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('sms_events', sa.Column('external_ref', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sms_events', sa.Column('channel', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('sms_events', sa.Column('failure_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sms_events', sa.Column('activation_status', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('sms_events', sa.Column('is_otp', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('sms_events', sa.Column('event_result', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('sms_events', sa.Column('otp_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('sms_events', sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sms_events', sa.Column('template_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sms_events', sa.Column('phone_number', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('sms_events', sa.Column('website_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('sms_events', sa.Column('template_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sms_events', sa.Column('activation_channel', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_sms_evt_user_id'), 'sms_events', ['user_id'], unique=False)
    op.create_index(op.f('idx_sms_evt_user_dt'), 'sms_events', ['user_id', 'event_datetime'], unique=False)
    op.create_index(op.f('idx_sms_evt_service_id'), 'sms_events', ['service_id'], unique=False)
    op.create_index(op.f('idx_sms_evt_service_dt'), 'sms_events', ['service_id', 'event_datetime'], unique=False)
    op.create_index(op.f('idx_sms_evt_otp_partial'), 'sms_events', ['event_datetime'], unique=False, postgresql_where='(is_otp = true)')
    op.create_index(op.f('idx_sms_evt_is_otp'), 'sms_events', ['is_otp'], unique=False)
    op.create_index(op.f('idx_sms_evt_is_activation'), 'sms_events', ['is_activation'], unique=False)
    op.create_index(op.f('idx_sms_evt_failed_delivery_partial'), 'sms_events', ['event_datetime'], unique=False, postgresql_where="((delivery_status)::text = 'FAILED'::text)")
    op.create_index(op.f('idx_sms_evt_event_type'), 'sms_events', ['event_type'], unique=False)
    op.create_index(op.f('idx_sms_evt_event_datetime'), 'sms_events', ['event_datetime'], unique=False)
    op.create_index(op.f('idx_sms_evt_dt_channel'), 'sms_events', ['event_datetime', 'channel'], unique=False)
    op.create_index(op.f('idx_sms_evt_delivery_status_dt'), 'sms_events', ['delivery_status', 'event_datetime'], unique=False)
    op.create_index(op.f('idx_sms_evt_delivery_status'), 'sms_events', ['delivery_status'], unique=False)
    op.create_index(op.f('idx_sms_evt_channel'), 'sms_events', ['channel'], unique=False)
    op.create_index(op.f('idx_sms_evt_activation_partial'), 'sms_events', ['event_datetime'], unique=False, postgresql_where='(is_activation = true)')
    op.create_index(op.f('idx_sms_evt_activation_channel_dt'), 'sms_events', ['activation_channel', 'event_datetime'], unique=False)
    op.create_index(op.f('idx_sms_evt_activation_channel'), 'sms_events', ['activation_channel'], unique=False)
    op.create_index(op.f('idx_sms_events_source_system'), 'sms_events', ['source_system'], unique=False)
    op.create_index(op.f('idx_sms_events_metadata_gin'), 'sms_events', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_sms_events_event_type_event_datetime'), 'sms_events', ['event_type', sa.literal_column('event_datetime DESC')], unique=False)
    op.alter_column('sms_events', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_platform_users_reset_token'), 'platform_users', ['reset_token'], unique=False)
    op.alter_column('platform_users', 'reset_token_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Expiration du token de réinitialisation',
               existing_nullable=True)
    op.alter_column('platform_users', 'reset_token',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Token de réinitialisation de mot de passe',
               existing_nullable=True)
    op.drop_table_comment(
        'platform_user_invites',
        existing_comment='Pending platform user invites',
        schema=None
    )
    op.create_index(op.f('idx_cohorts_service_id'), 'cohorts', ['service_id'], unique=False)
    op.create_index(op.f('idx_cohorts_service_cohort_date'), 'cohorts', ['service_id', 'cohort_date'], unique=False)
    op.create_index(op.f('ix_campaigns_service_send_datetime'), 'campaigns', ['service_id', 'send_datetime'], unique=False)
    op.create_index(op.f('idx_campaigns_service_send_datetime'), 'campaigns', ['service_id', 'send_datetime'], unique=False)
    op.create_index(op.f('ix_be_subscription_event_status'), 'billing_events', ['subscription_id', sa.literal_column('event_datetime DESC'), 'status'], unique=False)
    op.create_index(op.f('idx_billing_events_user_datetime'), 'billing_events', ['user_id', 'event_datetime'], unique=False)
    op.create_index(op.f('idx_billing_events_sub_success_dt'), 'billing_events', ['subscription_id', 'event_datetime'], unique=False, postgresql_where="((status)::text = 'success'::text)")
    op.create_index(op.f('idx_billing_events_sub_failed_dt'), 'billing_events', ['subscription_id', 'event_datetime'], unique=False, postgresql_where="((status)::text = 'failed'::text)")
    op.create_index(op.f('idx_billing_events_service_datetime'), 'billing_events', ['service_id', 'event_datetime'], unique=False)
    op.create_index(op.f('idx_billing_events_datetime_status'), 'billing_events', ['event_datetime', 'status'], unique=False)
    op.drop_table_comment(
        'analyst_notes',
        existing_comment='Analyst contextual notes',
        schema=None
    )
    op.create_table('user_features',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('active_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('churn_flag', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('segment', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('user_features_pkey')),
    comment='Precomputed feature store for segmentation analytics'
    )
    op.create_index(op.f('idx_user_features_updated_at'), 'user_features', ['updated_at'], unique=False)
    op.create_index(op.f('idx_user_features_segment'), 'user_features', ['segment'], unique=False)
    op.create_index(op.f('idx_user_features_churn_segment'), 'user_features', ['churn_flag', 'segment'], unique=False)
    op.create_table('segmentation_training_jobs',
    sa.Column('job_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('service_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('model_version', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('best_k', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('silhouette_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('job_id', name=op.f('segmentation_training_jobs_pkey'))
    )
    op.create_index(op.f('ix_seg_train_jobs_started_at'), 'segmentation_training_jobs', [sa.literal_column('started_at DESC')], unique=False)
    op.create_table('segmentation_training_job_logs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['segmentation_training_jobs.job_id'], name=op.f('segmentation_training_job_logs_job_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('segmentation_training_job_logs_pkey'))
    )
    op.create_index(op.f('ix_seg_train_logs_job_id'), 'segmentation_training_job_logs', ['job_id', sa.literal_column('ts DESC')], unique=False)
    op.create_table('segmentation_assignments',
    sa.Column('model_version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('segment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('cluster_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('revenue_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('avg_revenue_30d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('active_days_30d', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('has_churn', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('window_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('window_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('model_version', 'user_id', name=op.f('segmentation_assignments_pkey'))
    )
    op.create_index(op.f('ix_seg_assign_service_win'), 'segmentation_assignments', ['service_id', 'window_start', 'window_end', sa.literal_column('generated_at DESC')], unique=False)
    op.create_index(op.f('ix_seg_assign_generated_at'), 'segmentation_assignments', [sa.literal_column('generated_at DESC')], unique=False)
    op.create_table('churn_scores_cache',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('service_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('churn_risk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('risk_category', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('predicted_churn', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('churn_scores_cache_pkey'))
    )
    op.create_index(op.f('ix_churn_scores_cache_risk'), 'churn_scores_cache', [sa.literal_column('churn_risk DESC')], unique=False)
    op.create_index(op.f('ix_churn_scores_cache_generated_at'), 'churn_scores_cache', [sa.literal_column('generated_at DESC')], unique=False)
    op.create_table('campaign_targets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('campaign_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('segment', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('campaign_targets_campaign_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('campaign_targets_pkey')),
    sa.UniqueConstraint('campaign_id', 'phone_number', name=op.f('uq_campaign_targets_campaign_phone'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_ct_phone'), 'campaign_targets', ['phone_number'], unique=False)
    op.create_index(op.f('idx_ct_campaign'), 'campaign_targets', ['campaign_id'], unique=False)
    op.create_table('staging_imports',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('import_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('row_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('staging_imports_pkey'))
    )
    # ### end Alembic commands ###
